export const BREAKPOINTXS = 0;

export const BREAKPOINTSTORYBOOKSMALLMOBILEL = 600;

export const BREAKPOINTSM = 600;

export const BREAKPOINTSTORYBOOKLARGEMOBILEL = 896;

export const BREAKPOINTMD = 900;

export const BREAKPOINTSTORYBOOKTABLETL = 1112;

export const BREAKPOINTLG = 1200;

export const BREAKPOINTSTORYBOOKDESKTOP = 1200;

export const BREAKPOINTXL = 1536;